baseURL = 'https://iamsharpe.github.io/'
locale = 'zh-cn'
title = '谢鹏个人博客'
theme = "PaperMod"

[params]
  author = "谢鹏"
  defaultTheme = "auto"
  homeInfoParams={Title="欢迎来到我的博客",Content="记录技术笔记与生活感悟"}
